<?php

/**
 * @file
 * Primary module hooks for custom_secret_key module.
 */

/**
 * Implements hook_uninstall() for custom_secret_key module.
 */
function custom_secret_key_uninstall() {
  // Delete the custom_domain_verifier.settings file.
  $config_path = \Drupal::configFactory()->getEditable('custom_secret_key.settings');
  if ($config_path->isNew()) {
    $config_path->delete();
    \Drupal::messenger()->addMessage(t('custom_secret_key.settings file has been deleted.'));
  }

}
